### ISSUE TITLE
Preview apps action fails on the first run

### ISSUE THREAD

**Issue by kikkupico** [hasura/hasura-cloud-preview-apps#114]
## Bug

Preview app action fails on the first run with the error `Error: could not find the GitHub job; the associated deployment was terminated`

## Workaround

This is fixed by re-running the job.

## Expected

The action should run successfully every time (if configured correctly).

## Examples

https://github.com/kikkupico/samp-home-food-dev-2/runs/7148915232?check_suite_focus=true

## Related

https://github.com/hasura/hasura-cloud-preview-apps/issues/91

**Comment by jasongoetz** [comment]
I have been experiencing the same issue. Is this happening with everyone? I don't imagine there is any way around this right now.

**Comment by sfarqu** [comment]
Thank you for bringing this issue up, and apologies for lack of response so far. I've raised a ticket internally to investigate this, will update here with any progress.

**Comment by jasongoetz** [comment]
This issue now happens for us on every single run. Re-running the job leads to the same error. `Error: could not find the GitHub job; the associated deployment was terminated` 

We have the need to configure Vercel and Hasura together in our preview environments so they are aware of each other's URLs. So a custom action is necessary if we're going to have preview environments that work.

Should I try to work with the Preview Apps API instead? Would that give me any more success? https://hasura.io/docs/latest/deployment/hasura-cloud/ci-cd/preview-apps/#preview-apps-api

**Comment by osdiab** [comment]
Mentioning considerably later, this is still happening. Is it safe to assume that this project is dead at Hasura?

**Comment by osdiab** [comment]
So after trying to add more logging to the actual action, I find nothing helpful - basically

- the GQL query itself doesn't throw anything
- it just returns a `null` value

my best guess is that it's querying too early before the job exists in Hasura's system (or there's some bug in how the querying logic works maybe). so maybe a reasonable approach would be to just have it retry a few times instead of erroring immediately to give the system a chance to properly return this value.

**Comment by osdiab** [comment]
Tried retrying 3 times with 2 second time outs, that didn't do the trick. trying retrying up to 10 times. I'm also finding that this isn't consistently just on the first run, when i retry jobs it sometimes happens again for... reasons
